services:
  # nextjs:
  #   build:
  #     context: ./
  #     target: runner
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   command: npm run dev
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     NODE_ENV: development

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_DB=idens-online
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/db:/var/lib/postgresql/data
    ports:
      - 5432:5432